version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/agenda/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 600
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 600
     runas: root